### ISSUE TITLE
rsync: only REMOVE Event received

### ISSUE THREAD

**Issue by kontrafiktion** [go-fsnotify/fsevents#11]
Hi!

With a very simple test (on OS X):

```
package main

import (
	"fmt"
	"strings"
	"gopkg.in/fsnotify.v1"
)


func main() {
	watcher, err := fsnotify.NewWatcher()
	if err != nil {
		fmt.Printf("fsnotify.NewWatcher() creates error=<%v>", err)
	}
	fileorfolder := "/tmp/watchme.dir"
	fmt.Printf("watching %s\n", fileorfolder)
	err = watcher.Add(fileorfolder)
	if err != nil {
		fmt.Printf("watcher.Watch subfolder=<%v> error=<%v>", fileorfolder, err)
	}

	loop:
	for {
		select {
		case ev := <-watcher.Events:
			fmt.Printf("event %s\n", ev)
		    if strings.Contains(ev.Name, "Bye") {
				break loop
			}
		case err := <-watcher.Errors:
			fmt.Printf("error: " + err.Error())
		    break loop
		}
	}
}
```

and using rsync (`rsync -avh  /tmp/rsync.test/watchme.dir /tmp`) to "copy" files ("foo.txt") to the watched location, I get 

    event "/tmp/watchme.dir/foo.txt": REMOVE

but nothing else. I would have expected a MOVE or CREATE for the file. On Linux I get

    event "/tmp/watchme.dir/.foo.txt.HM02fS": CREATE
    event "/tmp/watchme.dir/.foo.txt.HM02fS": CHMOD
    event "/tmp/watchme.dir/.foo.txt.HM02fS": RENAME
    event "/tmp/watchme.dir/foo.txt": CREATE

**Comment by nathany** [comment]
It looks like this is an issue on https://github.com/go-fsnotify/fsnotify, not fsevents?

Have you tried putting the for loop in a goroutine like in the example? 
https://github.com/go-fsnotify/fsnotify/blob/master/example_test.go

**Comment by kontrafiktion** [comment]
Ah, sorry mixed it up
